version: '3'

services:

  jakes-blokus-web:
      container_name: "jakes-blokus-web"
      build:
          context: ./
      volumes:
          - ./nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
          - 8088:80
      restart: unless-stopped
